# see hooks/build and hooks/.config
ARG BASE_IMAGE_PREFIX
FROM ${BASE_IMAGE_PREFIX}alpine:edge as builder

# see hooks/post_checkout
ARG ARCH
COPY qemu-${ARCH}-static /usr/bin

RUN uname -ar > /uname.build
COPY cow.c cow.c
RUN apk update ; apk add gcc
RUN gcc cow.c -o cow

FROM scratch
ARG ARCH
COPY --from=0 cow .

ENTRYPOINT ["./cow", ""]
