# see hooks/build and hooks/.config
ARG BASE_IMAGE_PREFIX
FROM ${BASE_IMAGE_PREFIX}alpine:edge as builder

# see hooks/post_checkout
ARG ARCH
COPY qemu-${ARCH}-static /usr/bin

RUN uname -ar > /uname.build
RUN apk update ; apk add wget
RUN wget https://github.com/Code-Hex/Neo-cowsay/releases/download/v1.0.1/cowsay_v1.0.1_Linux_x86_64.tar.gz
RUN tar -xf cowsay_v1.0.1_Linux_x86_64.tar.gz

FROM scratch
ARG ARCH
COPY --from=0 cowsay .

ENTRYPOINT ["./cowsay", ""]
